name = "lokly"
main = "src/index.ts"
compatibility_date = "2026-04-07"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "lokly.heydeyo.lol/*", zone_id = "b8614434c0ce1ff1191664e84e736899" },
  { pattern = "*-lokly.heydeyo.lol/*", zone_id = "b8614434c0ce1ff1191664e84e736899" },
]

[[durable_objects.bindings]]
name = "TUNNEL_DO"
class_name = "TunnelDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TunnelDO"]

[observability.logs]
enabled = true
invocation_logs = true
